[project]
name = "steam-game-update-monitor" 
version = "0.1.0"
description = "Steam game update check"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-telegram-bot>=22.5",
    "vdf>=3.4",
]
